services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 8081:8080
    environment:
      - FRONTEND_BASE_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres:password@db-test:5432/database
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
      - /app/prisma/migrations
    depends_on:
      - db-test

  db-test:
    image: postgis/postgis:15-3.3
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_test_data:/var/lib/postgresql/data # DBデータの永続化

volumes:
  postgres_test_data: # テスト用DBのボリューム
